version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_dev
    environment:
      POSTGRES_DB: ${DB_NAME:-myapp_dev}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis_cache_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - app-network

  # Server (Development)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: app_server_dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-password}@postgres:5432/${DB_NAME:-myapp_dev}
      - REDIS_URL=redis://redis:6379
    ports:
      - "5000:5000"
      - "9229:9229"  # Debug port
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    networks:
      - app-network
    command: npm run dev

  # Client (Development)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: app_client_dev
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  app-network:
    driver: bridge
